// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day41Demo.DataAccess.Models
{
    [Table("persons")]
    public partial class Person
    {
        [Key]
        [Column("person_id")]
        public int PersonId { get; set; }
        [Required]
        [Column("first_name")]
        [StringLength(100)]
        public string FirstName { get; set; }
        [Required]
        [Column("last_name")]
        [StringLength(100)]
        public string LastName { get; set; }
        [Column("dob", TypeName = "date")]
        public DateTime? Dob { get; set; }
    }
}