// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Day41Demo.DataAccess.Models
{
    [Table("targets", Schema = "sales")]
    public partial class Target
    {
        public Target()
        {
            Commissions = new HashSet<Commission>();
        }

        [Key]
        [Column("target_id")]
        public int TargetId { get; set; }
        [Column("percentage", TypeName = "decimal(4, 2)")]
        public decimal Percentage { get; set; }

        [InverseProperty("Target")]
        public virtual ICollection<Commission> Commissions { get; set; }
    }
}